name: Check for ALTER or UPDATE commands in SQL files

on:
  pull_request:
    paths:
      - '**/*.sql'
    types: [opened, synchronize, reopened]

jobs:
  check-sql-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Get list of changed SQL files
        run: |
          # Use the dynamic GitHub context variables for comparing branches
          echo "Comparing branches: ${GITHUB_BASE_REF}...${GITHUB_HEAD_REF}"
          git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} > changed_files.txt
          cat changed_files.txt

      - name: Check for ALTER or UPDATE commands in SQL files
        id: check_sql
        run: |
          commands_found=false
          message=""
          while IFS= read -r file; do
            if [[ "$file" == *.sql ]]; then
              echo "Checking file: $file"
              if grep -q -E 'UPDATE|ALTER' "$file"; then
                echo "Detected UPDATE or ALTER command in $file"
                commands_found=true
                message+="Detected UPDATE, ALTER, DROP, or ADD in $file\n"
              fi
            fi
          done < changed_files.txt

          echo "::set-output name=commands_found::$commands_found"
          echo "::set-output name=alert_message::$message"

      - name: Create GitHub Issue
        uses: octokit/request-action@v2.x
        with:
         script: |
          const { github, context } = require('@actions/github');
          if (!context.payload.pull_request) {
            throw new Error('Pull request data is not available in the current event context.');
          }

          const title = context.payload.pull_request.title || 'No Title';
          const url = context.payload.pull_request.html_url || 'No URL';

          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `PR Merged: ${title}`,
            body: `This issue is to notify the team about the recent changes:\n- **Title:** ${title}\n- **URL:** ${url}`,
            labels: ['notification']
          });

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
